version: '3'
services:
    poll:
        build:
            context: poll
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
    redis:
        image: "redis:alpine"
        expose:
            - "6379"
  # worker:
  # db:
    result:
        build:
            context: result
            dockerfile: Dockerfile
        ports:
            - "5001:5001"
volumes:
    dbdata: